version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building project...
      - npm run build
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync out/ s3://staticwebsitebucket-21303  --delete